name: Compilar APK Buscador GH

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar motor de Android y Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade pip setuptools virtualenv
          pip install buildozer Cython==0.29.33

      - name: Compilar el APK
        run: yes | buildozer -v android debug

      - name: Entregar el APK terminado
        uses: actions/upload-artifact@v4
        with:
          name: BuscadorGH_APK
          path: bin/*.apk
